### ISSUE TITLE
输入可以支持指定一个目录里面的所有.en.json 类型的文件吗.然后输出在同目录为 .zh.json

### ISSUE THREAD

**Issue by clijiac** [hymhub/language-translate#1]
如题.
eg.  目录里有a.en.json, b.en.json
想要输出对应的a.th.json 等等

能支持子目录的话就更好了

**Comment by hymhub** [comment]
这是个不错的提议，下个版本增加这个功能

**Comment by hymhub** [comment]
> 

新版v2.1.2已发布，支持动态路径解析，可以递归翻译文件夹了哦~ 链接: [https://github.com/hymhub/language-translate#%E9%AB%98%E7%BA%A7%E7%94%A8%E6%B3%95](https://github.com/hymhub/language-translate#%E9%AB%98%E7%BA%A7%E7%94%A8%E6%B3%95)

**Comment by clijiac** [comment]
牛逼! 立即试用一哈.

**Comment by clijiac** [comment]
完美..
