### ISSUE TITLE
翻译成功后，想做增量翻译，发现解析生成后的目标翻译文件有问题？

### ISSUE THREAD

**Issue by zhounew** [hymhub/language-translate#10]
我通过en.json翻译到了ja.json，然后更新了en.json，执行npm run translate，说：
`
翻译异常: 检查目标文件内是否有错误
 path ---> C:\projects\internwork\intern-zgr\locale-test\locales\ja.json
SyntaxError: Unexpected number
`
我测试了en.json和ja.json都是正确格式的json文件，可以被正常格式化，这是什么原因啊？

![image](https://github.com/hymhub/language-translate/assets/8465627/d626e6af-0b15-4c76-9bff-b6ead2d5df21)

**Comment by hymhub** [comment]
能提供一下 en.json 文案吗

**Comment by zhounew** [comment]
可以的，我单独发给你邮箱吧，发到你的hyminghan@gmail.com邮箱了。

**Comment by hymhub** [comment]
> 可以的，我单独发给你邮箱吧，发到你的[hyminghan@gmail.com](mailto:hyminghan@gmail.com)邮箱了。

没有收到哦

**Comment by zhounew** [comment]
您再看下，我发给您了，包括我的工程代码。

**Comment by hymhub** [comment]
> 您再看下，我发给您了，包括我的工程代码。

还是没收到哦，检查下是否发错人了呢，或者发送hyminghan@outlook.com试试

**Comment by hymhub** [comment]
现在最新版是 v2.1.10 哦，你用的是旧版 
![image](https://github.com/hymhub/language-translate/assets/68531467/702119de-75da-4e2c-8007-25f060dc9ce1)
