### ISSUE TITLE
提供一个开关, 只更新在目标json中key对应的值是空或者key不存在的记录,已有的不动,方便增量更新

### ISSUE THREAD

**Issue by clijiac** [hymhub/language-translate#3]

**Comment by hymhub** [comment]
ok，下个版本增加，会和你提交的 pr 在一个版本内发布

**Comment by hymhub** [comment]
新版 v2.1.3 已发布， 配置中查看 incrementalMode：[https://github.com/hymhub/language-translate#translateconfigjsts](https://github.com/hymhub/language-translate#translateconfigjsts)

**Comment by clijiac** [comment]
> 新版 v2.1.3 已发布， 配置中查看 incrementalMode：https://github.com/hymhub/language-translate#translateconfigjsts

牛的. 明天起来试用下,感觉已经完美了
