### ISSUE TITLE
严重bug：部分翻译的json，有关键词冲突

### ISSUE THREAD

**Issue by zhounew** [hymhub/language-translate#7]
比如要翻译的json为：
{
    "common": {
        "export": "Export"
    }
}

会报错：
翻译异常: 请检查待翻译文件内容是否正常
path ---> c:\projects\internwork\intern-zgr\locale-test\locales\en\en.json

如果我把 export 改为：expor，则不会报错。怀疑是是代码对export等关键词识别错误。

**Comment by hymhub** [comment]
已修复

**Comment by zhounew** [comment]
谢谢，已经double check过，确实已修复！
