### ISSUE TITLE
json文件中，message太多，会导致运行卡死。

### ISSUE THREAD

**Issue by zhounew** [hymhub/language-translate#8]
首先，感谢作者做了一个我正准备想写的一个国际化工具，而且你这功能做得很细很强大！匠工精神！正在试用的过程中发现：

当要翻译的一个message的字符串内容太多的时候，用google翻译引擎，会出现卡死和“翻译失败，正在重试中.....”的情况，我的message大概有2000多个，翻译成多个国家语言，会出现卡死。

如果是因为google翻译引擎不能调用太快，可以考虑sleep 200-500ms。以及怎么解决下卡死的问题？至少可以重试（比如每次都写下磁盘dump成json，后面已经翻译的就不翻译了，类似您说的fast mode），这如果message太多的话，会导致中途断了，还要重试。

另外给一个建议，目前一个message是根据配置来进行多个国家语言翻译，这样如果中间任何一个字符串翻译卡死，那所有国家语言就要重来，是不是可以一个语言包弄完一个，再弄一个，这样也可以避免这种问题，以及节省内存，因为好像咱们是先写内存，最后完成后再写磁盘。（因为我们产品会支持30多种语言。。。）

![image](https://github.com/hymhub/language-translate/assets/8465627/9d1bda32-83f3-49d7-b635-439eda67bbf1)

**Comment by hymhub** [comment]
在翻译完成之前目前确实是直接写内存，没同步硬盘，一次性翻译量太大确实可能出现爆内存的情况，可以先人工把需要翻译的文案拆分成多次翻译临时解决你的需求，同时如果30个语言同时翻译也就意味着一个 key 文案翻译时会异步并行请求30次 确实可能发生接口调用频繁问题，可以配置翻译启动时终端自定义可选功能（https://github.com/hymhub/language-translate#faq）或者手动分多次进行，例如一个选项配置10种语言，分3次翻译来临时解决你的问题。

同时下个版本会对上诉问题进行优化修复😃

**Comment by hymhub** [comment]
在翻译完成之前目前确实是直接写内存，没同步硬盘，一次性翻译量太大确实可能出现爆内存的情况，可以先人工把需要翻译的文案拆分成多次翻译临时解决你的需求，同时如果30个语言同时翻译也就意味着一个 key 文案翻译时会异步并行请求30次 确实可能发生接口调用频繁问题，可以配置翻译启动时终端自定义可选功能（https://github.com/hymhub/language-translate#faq）或者手动分多次进行，例如一个选项配置10种语言，分3次翻译来临时解决你的问题。

同时下个版本会对上诉问题进行优化修复，可能采用队列方式限制接口请求并发上限和一次性翻译大量文案分片同步硬盘达到定期释放内存的效果😃

**Comment by zhounew** [comment]
我有一个思路，原本我是想这么做的，可以解决批处理快速翻译的问题，您可以参考下这个算法：

1. 把json中的文案，全部转义出来，通过遍历key深度，将一个原始json：
```
{
    "title": "hello, world",
    "code": "error happens",
    "child": {
          "subtitle": "child's tilte"
    },
} 
```
变成按行排列的字符串：
```
"title": "hello, world",
"code": "error happens",
"child||subtitle": "child's title"
```

然后再转化为：
```
hello, world
error happens
child's title
```

把这份文档批量发到google的翻译引擎（由于其有字数限制，我们可以通过程序来判断一次性喂多少行），就可以一次性拿到所有的翻译结果，也是按行分隔的。
这是比如得到日语的结果：

```
こんにちは世界
エラーが発生する
子供の称号
```

然后通过程序反向变为：
```
"title": "こんにちは世界",
"code": "エラーが発生する"
"child||subtitle": "子供の称号"
```

然后再通过一个dfs的遍历，重构json的格式，变成：
```
{
    "title": "こんにちは世界",
    "code": "エラーが発生する",
    "child": {
          "subtitle": "子供の称号"
    },
} 
```

3. 这种方法，可以避免每次都按一个json的一个key-value来扔到google的翻译引擎，可以批量处理文档。速度也会比现在快很多。
4. json字符串的json2string的代码和反解析json的string2json代码，我写了一个，您可以参考啊，我觉得可以集成进入到你的这个工具里面去，做国际化的工程太需要了。在线等您的修改哈，这样我的几千行的语言包的json就可以通过您的代码快速翻译处理了。

```
json2string(str) {
                // 为了解决部分用单引号，而不是双引号的key
                let reg = /("([^\\\\"]*(\\.)?)*")|('([^\\\\']*(\\.)?)*')|(\/{2,}.*?(\r|\n|$))|(\/\*(\n|.)*?\*\/)/g;
                str = str.replace(reg, function(word) {
                    return /^\/{2,}/.test(word) || /^\/\*/.test(word) ? "" : word;
                });

                str = str.replaceAll(/: '/, ":\"");
                str = str.replaceAll(/:'/, ":\"");
                str = str.replaceAll(/',/, "\",");

                str = str.replace(/(\s*?{\s*?|\s*?,\s*?)(['"])?([a-zA-Z0-9_]+)(['"])?:/g, '$1"$3":');
                let obj = JSON.parse(str);
                let result = {};
                this.dfsObj(obj, '', result);
                let resultStr = "";
                Object.keys(result).forEach(key => {
                    resultStr += '"{0}": "{1}"\n'.format(key, result[key]);
                });
                return resultStr;
            },

            dfsObj(obj, prefix, result) {
                if (obj instanceof Object) {
                    Object.keys(obj).forEach((key) => {
                        this.dfsObj(obj[key], prefix + "___" + key, result);
                    });
                } else {
                    result[prefix] = obj;
                }
            },

            onText2Json(str) {
                let obj = {};
                let tmpObj = obj;
                let lines = str.split('\n');
                lines.forEach(line => {
                    let tmp = line.split('": "');
                    if (tmp.length < 2) {
                        return;
                    }
                    let key = tmp[0].replace("\"", "");
                    let value = tmp[1].replace("\"", "");
                    let tokens = key.split('___');
                    tokens.splice(0, 1);
                    this.dfsStr2Obj(tokens, 0, value, obj);
                });
                return  JSON.stringify(tmpObj);
            },

            dfsStr2Obj(strArray, i, value, obj) {
                if (i < strArray.length-1) {
                    let key = strArray[i];
                    if (!Object.hasOwn(obj, key)) {
                        obj[key] = {};
                    }
                    this.dfsStr2Obj(strArray, i + 1, value, obj[key]);
                } else {
                    let key = strArray[i];
                    obj[key] = value;
                }
            }



```

期待您的更新啊，这个工具写的特别棒！

**Comment by zhounew** [comment]
目前即使我拆分出来单独用日语，也会出现卡死的问题，没法完成我的json语言包的翻译。。。



![image](https://github.com/hymhub/language-translate/assets/8465627/0237ac97-6cc7-4e15-8005-4707d16759f5)

**Comment by hymhub** [comment]
> 我有一个思路，原本我是想这么做的，可以解决批处理快速翻译的问题，您可以参考下这个算法：
> 
> 1. 把json中的文案，全部转义出来，通过遍历key深度，将一个原始json：
> ```
> {
>     "title": "hello, world",
>     "code": "error happens",
>     "child": {
>           "subtitle": "child's tilte"
>     },
> } 
> ```
> 变成按行排列的字符串：
> ```
> "title": "hello, world",
> "code": "error happens",
> "child||subtitle": "child's title"
> ```
> 
> 然后再转化为：
> ```
> hello, world
> error happens
> child's title
> ```
> 
> 把这份文档批量发到google的翻译引擎（由于其有字数限制，我们可以通过程序来判断一次性喂多少行），就可以一次性拿到所有的翻译结果，也是按行分隔的。
> 这是比如得到日语的结果：
> 
> ```
> こんにちは世界
> エラーが発生する
> 子供の称号
> ```
> 
> 然后通过程序反向变为：
> ```
> "title": "こんにちは世界",
> "code": "エラーが発生する"
> "child||subtitle": "子供の称号"
> ```
> 
> 然后再通过一个dfs的遍历，重构json的格式，变成：
> ```
> {
>     "title": "こんにちは世界",
>     "code": "エラーが発生する",
>     "child": {
>           "subtitle": "子供の称号"
>     },
> } 
> ```
> 
> 3. 这种方法，可以避免每次都按一个json的一个key-value来扔到google的翻译引擎，可以批量处理文档。速度也会比现在快很多。
> 4. json字符串的json2string的代码和反解析json的string2json代码，我写了一个，您可以参考啊，我觉得可以集成进入到你的这个工具里面去，做国际化的工程太需要了。在线等您的修改哈，这样我的几千行的语言包的json就可以通过您的代码快速翻译处理了。
> 
> ```
> json2string(str) {
>                 // 为了解决部分用单引号，而不是双引号的key
>                 let reg = /("([^\\\\"]*(\\.)?)*")|('([^\\\\']*(\\.)?)*')|(\/{2,}.*?(\r|\n|$))|(\/\*(\n|.)*?\*\/)/g;
>                 str = str.replace(reg, function(word) {
>                     return /^\/{2,}/.test(word) || /^\/\*/.test(word) ? "" : word;
>                 });
> 
>                 str = str.replaceAll(/: '/, ":\"");
>                 str = str.replaceAll(/:'/, ":\"");
>                 str = str.replaceAll(/',/, "\",");
> 
>                 str = str.replace(/(\s*?{\s*?|\s*?,\s*?)(['"])?([a-zA-Z0-9_]+)(['"])?:/g, '$1"$3":');
>                 let obj = JSON.parse(str);
>                 let result = {};
>                 this.dfsObj(obj, '', result);
>                 let resultStr = "";
>                 Object.keys(result).forEach(key => {
>                     resultStr += '"{0}": "{1}"\n'.format(key, result[key]);
>                 });
>                 return resultStr;
>             },
> 
>             dfsObj(obj, prefix, result) {
>                 if (obj instanceof Object) {
>                     Object.keys(obj).forEach((key) => {
>                         this.dfsObj(obj[key], prefix + "___" + key, result);
>                     });
>                 } else {
>                     result[prefix] = obj;
>                 }
>             },
> 
>             onText2Json(str) {
>                 let obj = {};
>                 let tmpObj = obj;
>                 let lines = str.split('\n');
>                 lines.forEach(line => {
>                     let tmp = line.split('": "');
>                     if (tmp.length < 2) {
>                         return;
>                     }
>                     let key = tmp[0].replace("\"", "");
>                     let value = tmp[1].replace("\"", "");
>                     let tokens = key.split('___');
>                     tokens.splice(0, 1);
>                     this.dfsStr2Obj(tokens, 0, value, obj);
>                 });
>                 return  JSON.stringify(tmpObj);
>             },
> 
>             dfsStr2Obj(strArray, i, value, obj) {
>                 if (i < strArray.length-1) {
>                     let key = strArray[i];
>                     if (!Object.hasOwn(obj, key)) {
>                         obj[key] = {};
>                     }
>                     this.dfsStr2Obj(strArray, i + 1, value, obj[key]);
>                 } else {
>                     let key = strArray[i];
>                     obj[key] = value;
>                 }
>             }
> 
> 
> 
> ```
> 
> 期待您的更新啊，这个工具写的特别棒！

这个思路很棒，最初就考虑过这个方案，但行不通，有时候文案翻译后由于各种语言语法不同导致结果会错位，也想过用某个特殊字符去做标记，但是有时候又会把特殊字符翻译成不期望的样子，或者文案本身存在特殊字符或者换行等等，边缘情况太多，处理不了，现在这样翻译也不太影响效率，设计之初是考虑新项目一开始不会有太多文案，然后迭代一下新增或修改一些文案，目前工具增量更新完全能满足。现在用于一次性翻译很多文案 key，可能会造成你说的卡死或者翻译失败情况，下个版本会做分片处理，在翻译过程中定期同步写入硬盘释放内存避免卡死或者翻译失败又全部重试的问题

**Comment by hymhub** [comment]
> 目前即使我拆分出来单独用日语，也会出现卡死的问题，没法完成我的json语言包的翻译。。。
> 
> 
> 
> ![image](https://github.com/hymhub/language-translate/assets/8465627/0237ac97-6cc7-4e15-8005-4707d16759f5)
> 

语言不用单个单个翻译，一次性翻译10个语言应该不成问题 先把文案拆分一下，比如一次翻译0-99个key，翻译完了再翻译100-200个key，还不行就0-49，50-100这样，相当于手动分片😂，下个版本会解决这些问题的

**Comment by zhounew** [comment]
谢谢您的回复，下个版本会什么时候出来啊？

**Comment by hymhub** [comment]
> 谢谢您的回复，下个版本会什么时候出来啊？

下班后或者周末有空会写的 哈哈 出来了在这里告诉你

**Comment by zhounew** [comment]
期待啊，看看今天能搞定不？我这文件手工分片太麻烦了。。。最好您这边能自动分片，并且把已翻译的结果能保存起来，不用重新跑了。

**Comment by hymhub** [comment]
![IMG_20230515_081456.png](https://github.com/hymhub/language-translate/assets/68531467/278c1a2e-0b54-4acf-a424-041154c751c7)

昨晚确认了一下，跟内存没有关系，翻译占用内存很小的，所谓的卡死是因为 API 接口调用频繁或者代理网络节点不稳定，更新最新版，现在翻译运行时会默认每隔5个 key 同步写入一下硬盘，配置也新增了 `translateRuntimeDelay`和`translateRuntimeChunkSize` https://github.com/hymhub/language-translate#translateconfigjsts

**Comment by zhounew** [comment]
谢谢！！我测试试下！
