### ISSUE TITLE
建议：可否提供“不翻译”的白名单？

### ISSUE THREAD

**Issue by zhounew** [hymhub/language-translate#9]
作者您好！实际翻译中，有些内容是不希望全局翻译的，比如像facebook、twitter、google这类，以及产品名称，就是品牌名，不希望在各类语言中翻译。这样，是否可以针对某些特定的key不做翻译，相当于是设定一个key的白名单，格式也是json格式，和正常的message bundle保持结构一致，这样翻译引擎就自动跳过，复制源文件的key和value。

**Comment by hymhub** [comment]
配置新增 `ignoreValuesAndCopyToTarget` ，只需配置 `ignoreValuesAndCopyToTarget: ['facebook', 'twitter', 'google']`，即可实现你的需求，注意，数组内是源文件中的 `value`
https://github.com/hymhub/language-translate#translateconfigjsts
